#!/usr/bin/env python3

import sys

def printUsage():
    print(f"Usage: {sys.argv[0]} str numMethod\n\nnumMethod:\n1: LIT+DEO\n2: LITERAL HEX RUNE\n3: (RAW CHARACTER RUNE / STRING RUNE) + LITERAL HEX FOR ( \\n )")
    sys.exit(1)

if len(sys.argv) != 3: printUsage()

if sys.argv[2] == "1":
    for x in sys.argv[1]: print(f"LIT {format(ord(x), "x")} LIT 18 DEO ( {x} )")
    print("LIT 0a LIT 18 DEO ( \\n )")

elif sys.argv[2] == "2":
    for x in sys.argv[1]: print(f"#{format(ord(x), "x")} #18 DEO ( {x} )")
    print("#0a #18 DEO ( \\n )")

elif sys.argv[2] == "3":
    for x in sys.argv[1]: print(f"LIT \"{x} #18 DEO ( {x} )")
    print("#0a #18 DEO ( \\n )")

else: printUsage()
